// Auto-generated by wallace_generator.py
module tb_wallace16_normal;
reg [15:0] a;
reg [15:0] b;
wire [31:0] row0;
wire [31:0] row1;
wire [33:0] got;
reg [31:0] want;
integer i;

wallace16_normal dut (.a(a), .b(b), .row0(row0), .row1(row1));
assign got = {2'b0, row0} + {2'b0, row1};

task check;
begin
    want = {{16{1'b0}}, a} * {{16{1'b0}}, b};
    #1;
    if (got !== {2'b0, want}) begin
        $display("FAIL a=%h b=%h got=%h want=%h", a, b, got, {2'b0, want});
        $fatal;
    end
end
endtask

initial begin
    a = 16'h0; b = 16'h0; check();
    a = 16'h1; b = 16'h1; check();
    a = {16{1'b1}}; b = 16'h1; check();
    a = 16'h1; b = {16{1'b1}}; check();
    a = {16{1'b1}}; b = {16{1'b1}}; check();
    a = 16'hAAAA; b = 16'h5555; check();
    for (i = 0; i < 500; i = i + 1) begin
        a = $random;
        b = $random;
        check();
    end
    $display("PASS");
    $finish;
end
endmodule
