// Auto-generated by wallace_generator.py
module wallace2_n3_5(
    input  [1:0] a,
    input  [1:0] b,
    output [3:0] row0,
    output [3:0] row1
);

wire pp_0_0, pp_0_1, pp_1_0, pp_1_1;

assign pp_0_0 = a[0] & b[0];
assign pp_0_1 = a[0] & b[1];
assign pp_1_0 = a[1] & b[0];
assign pp_1_1 = a[1] & b[1];


assign row0[0] = pp_0_0;
assign row0[1] = pp_0_1;
assign row0[2] = pp_1_1;
assign row0[3] = 1'b0;
assign row1[0] = 1'b0;
assign row1[1] = pp_1_0;
assign row1[2] = 1'b0;
assign row1[3] = 1'b0;

// No activity above product width.
endmodule

module comp53(input a, input b, input c, input d, input e, output s0, output s1, output s2);
wire [2:0] count;
assign count = {2'b00, a} + {2'b00, b} + {2'b00, c} + {2'b00, d} + {2'b00, e};
assign s0 = count[0];
assign s1 = count[1];
assign s2 = count[2];
endmodule

module comp32(input a, input b, input c, output sum, output carry);
assign sum = a ^ b ^ c;
assign carry = (a & b) | (a & c) | (b & c);
endmodule

module comp22(input a, input b, output sum, output carry);
assign sum = a ^ b;
assign carry = a & b;
endmodule
